on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Notification Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run-script build:production
